[project]
name = "paella"
version = "0.1.0"
description = "Add a short description here"
authors = ["Zihua Wu <zihuaw@nvidia.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
cuda-toolkit = ">=12.5.0,<12.6"
cmake = ">=3.29.6,<3.30"
llvm = "14.*"
clang = "14.*"
spdlog = "1.11.*"
python = "3.8.*"
setuptools = ">=70.1.1,<70.2"
llvmdev = "14.*"
ninja = ">=1.12.1,<1.13"
zlib = ">=1.3.1,<1.4"
cxx-compiler = ">=1.7.0,<1.8"
libboost-devel = ">=1.85.0,<1.86"
fmt = ">=9.1.0,<9.2"
